money_transfer/homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='index'),
]

money_transfer/money_transfer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('home/', include('homepage.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = [
        path(
            '__debug__/',
            include('debug_toolbar.urls'),
        ),
        *urlpatterns,
    ]

money_transfer/catalog/models.py
__all__ = ()

import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import Truncator
from django.utils.translation import gettext_lazy as _
from smart_selects.db_fields import ChainedForeignKey

from core.models import BaseNameNormalizedModel
from core.validators import validate_date_future


class RecordStatus(BaseNameNormalizedModel):
    class Meta:
        verbose_name = _('record status')
        verbose_name_plural = _('record statuses')


class RecordType(BaseNameNormalizedModel):
    class Meta:
        verbose_name = _('record type')
        verbose_name_plural = _('record types')


class RecordCategory(BaseNameNormalizedModel):
    record_types = models.ManyToManyField(
        RecordType,
        verbose_name=_('type'),
        related_name='categories',
        related_query_name='categories',
    )

    class Meta:
        verbose_name = _('record category')
        verbose_name_plural = _('record categories')


class RecordSubCategory(BaseNameNormalizedModel):
    categories = models.ManyToManyField(
        RecordCategory,
        verbose_name=_('sub category'),
        related_name='sub_categories',
        related_query_name='sub_categories',
    )

    class Meta:
        verbose_name = _('record sub category')
        verbose_name_plural = _('record sub categories')


class Record(models.Model):
    comment = models.TextField(
        _('comment'),
        max_length=65535,
        blank=True,
        null=True,
        help_text=_('Max length is 65535'),
    )
    created_at = models.DateField(
        _('creation date'),
        default=datetime.date.today,
        validators=(validate_date_future,),
    )
    total = models.PositiveIntegerField(
        _('total (rub.)'),
        help_text=_('Enter positive number'),
    )
    category = ChainedForeignKey(
        RecordCategory,
        chained_field='record_type',
        chained_model_field='record_types',
        on_delete=models.RESTRICT,
        verbose_name=_('category'),
        help_text=_('Select "Type" at first'),
    )
    status = models.ForeignKey(
        RecordStatus,
        models.SET_NULL,
        verbose_name=_('status'),
        blank=True,
        null=True,
    )
    sub_category = ChainedForeignKey(
        RecordSubCategory,
        chained_field='category',
        chained_model_field='categories',
        on_delete=models.RESTRICT,
        verbose_name=_('sub category'),
        help_text=_('Select "Category" at first'),
    )
    record_type = models.ForeignKey(
        RecordType,
        on_delete=models.RESTRICT,
        verbose_name=_('type'),
    )

    class Meta:
        default_related_name = 'records'
        verbose_name = _('cash flow record')
        verbose_name_plural = _('cash flow records')

    def __str__(self):
        return f'Record (CF) <{self.record_type} {self.total}>'

    def clean(self):
        super().clean()
        sub_categories = self.category.sub_categories
        categories = self.record_type.categories

        if not sub_categories.filter(id=self.sub_category.id).exists():
            raise ValidationError(
                {
                    Record.sub_category.field.name: _(
                        'Selected sub category'
                        " doesn't belong to the selected category.",
                    ),
                },
            )

        if not categories.filter(id=self.category.id).exists():
            raise ValidationError(
                {
                    Record.category.field.name: _(
                        'Selected category'
                        " doesn't belong to the selected record type.",
                    ),
                },
            )

    def short_comment(self):
        return Truncator(self.comment).chars(40)

    short_comment.short_description = _('short comment')

money_transfer/core/models.py
__all__ = ()

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import Truncator
from django.utils.translation import gettext_lazy as _

from core.utils import normalize_str


class BaseNameModel(models.Model):
    name = models.CharField(
        _('name'),
        max_length=64,
        help_text=_('Max length is 64'),
    )

    class Meta:
        abstract = True

    def __str__(self):
        return Truncator(self.name).chars(20)


class BaseNameNormalizedModel(BaseNameModel):
    name_normalize = models.CharField(
        _('name (normalized)'),
        max_length=64,
        help_text=_('Generated field based on "name" field'),
        blank=True,
        auto_created=True,
    )

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.name_normalize = normalize_str(self.name)
        super().save(*args, **kwargs)

    def clean(self):
        name_normalize = normalize_str(self.name)
        same_objects = self.__class__.objects.filter(
            name_normalize=name_normalize,
        ).exclude(pk=self.pk)
        if same_objects.exists():
            meta_class = self.__class__._meta
            class_name = meta_class.verbose_name.title()
            field_name = meta_class.get_field(
                'name_normalize',
            ).verbose_name.title()
            raise ValidationError(
                _('%(class_name)s with this %(field_name)s already exists.'),
                params={'class_name': class_name, 'field_name': field_name},
            )

        super().clean()

money_transfer/homepage/views.py
__all__ = ()

from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'homepage/index.html'

money_transfer/homepage/templates/homepage/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
  <h1>{% translate 'Homepage' %}</h1>
{% endblock %}

money_transfer/templates/base.html
{% load i18n static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-title" content="Money Transfer">
    <title>{% block "title" %}Money Transfer{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icons/site.webmanifest' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>

  <body class="d-flex flex-column vh-100">

    {% include 'includes/header.html' %}

    <main class="container">
      {% if messages %}
        {% include 'includes/messages.html' with messages=messages only %}
      {% endif %}

      {% block content %}{% translate 'No content' %}{% endblock %}
    </main>

    {% include 'includes/footer.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/language.js' %}"></script>
  </body>
</html>

money_transfer/templates/includes/change_language.html
{% load i18n %}

<form id="lang-change" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select class="form-select" name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
</form>

money_transfer/templates/includes/footer.html
{% load i18n static %}

<footer class="container py-3 my-4 mt-auto">
  <ul class="list-inline text-center border-bottom pb-3 mb-3">
    <li class="list-inline-item"><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102108261" target="_blank" class="link-secondary link-underline-opacity-0">{% translate "Personal data" %}</a></li>
    <li class="list-inline-item"><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102014512" target="_blank" class="link-secondary link-underline-opacity-0">{% translate "Consumer rights" %}</a></li>
  </ul>
</footer>

money_transfer/templates/includes/form.html
{% load i18n %}

{% for field in form %}
  <div class="mb-3 {% if field.errors %}text-danger{% endif %}">
    {% if field.label and not field.is_hidden %}
      <div class="form-label">{{ field.label }}</div>
    {% endif %}

    {{ field }}

    {% if field.errors %}
      <div>
        <ul>
          {% for error in field.errors %}
            <li>{{ error|escape }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  </div>
{% endfor %}

{% if form.non_field_errors %}
  <div class="text-danger">
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

money_transfer/templates/includes/header.html
{% load i18n static %}

<header class="container d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="{% url 'homepage:index' %}" class="d-flex align-items-center me-3 mb-md-0 me-md-auto text-dark text-decoration-none">
    <img src="{% static 'icons/favicon-32x32.png' %}" class="me-2" width="40" height="32" />
    <span class="fs-4">Money Transfer</span>
  </a>
  {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'homepage:index' %}" class="nav-link {% if view_name == 'homepage:index' %}disabled active{% endif %}" aria-current="page">{% translate "To main" %}</a></li>
      <li class="nav-item ms-2">{% include "includes/change_language.html" %}</li>
    </ul>
  {% endwith %}
</header>

money_transfer/templates/includes/messages.html
<div class="messages">
  {% for message in messages %}
    <p class="alert{% if message.tags %}{% if 'success' in message.tags %} alert-success{% else %} alert-danger{% endif %}{% endif %}">{{ message }}</p>
  {% endfor %}
</div>